[site]
title = "Tally"
description = "Tally is a real-time tournament scheduling dashboard designed for FIRST LEGO League (FLL) events. It integrates seamlessly with Google Sheets to provide live schedule updates, pit locations, and upcoming matches to teams and organizers."
favicon = "/favicon.png"

[author]
name = "Tally"
title = "Tally App"
avatar = "/bio.jpg"
