[site]
title = "Tally"
description = "Tally is a purpose-built scheduling app for FIRST LEGO League (FLL) tournaments. It simplifies event management by keeping teams, judges, and schedules perfectly in sync."
favicon = "/favicon.png"

[author]
name = "Tally"
title = "Tally App"
avatar = "/bio.jpg"
